### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by Bashkinator** [Foxandxss/angular-webpack-workflow#1]
Script throws "TypeError: Cannot assign to read only property 'canCollapseWhitespace' of true" 

It seems that the reason is changes in interface of [html-minifier](https://github.com/kangax/html-minifier), which is used by [html-webpack-plugin](https://github.com/ampedandwired/html-webpack-plugin) (ampedandwired/html-webpack-plugin#97)

Just replace "minify: BUILD" in html-webpack-plugin initialization to something like

```javascript
minify: BUILD ? 
            {
              "removeComments": true,
              "removeCommentsFromCDATA": true,
              "removeCDATASectionsFromCDATA": true,
              "collapseWhitespace": true,
              "minifyJS": true,
              "minifyCSS": true
            } : 
            false
```
https://github.com/kangax/html-minifier#options-quick-reference

**Comment by Foxandxss** [comment]
I wonder if it really makes sense to minify it or not. My friend @cesarandreu who runs the react version removed it.

**Comment by Bashkinator** [comment]
I agree, html-minify is not necessary for workflow. But the error needs to be fixed.

**Comment by Foxandxss** [comment]
Don't worry, will fix it in a bit.
